### ISSUE TITLE
Tooltip not properly rendering

### ISSUE THREAD

**Issue by amolkare** [Microsoft/PowerBI-visuals-sampleBarChart#7] opened 2016-11-30 11:29 UTC
The tool tip is not rendering at pointer location when the mouse pointer moved over the bar.
tried building package as well.
![image](https://cloud.githubusercontent.com/assets/3225249/20750695/33747398-b6c6-11e6-88c5-ff363d7ed387.png)

**Comment by AviSander** [comment] 2016-12-06 06:46
confirmed - we're actively fixing this issue. Thx!

**Comment by sau752** [comment] 2016-12-28 04:10
Is this issue fixed or still pending?

**Comment by AviSander** [comment] 2016-12-28 08:17
not fixed yet - working on it...

**Comment by weiweicui** [comment] 2017-02-25 10:47
it seems that somehow 1px in the plugin is bigger than 1px outside...
I just scale the coordinates in the makeTooltipEventArgs function to make them consistent, 
something like:
`let tooltipEventArgs: TooltipEventArgs<T> = {
                data: data,
                coordinates: mouseCoordinates.map(d => d * 1.1667),
                elementCoordinates: elementCoordinates,
                context: target,
                isTouchEvent: isTouchEvent
};`

**Comment by AviSander** [comment] 2017-02-26 06:45
Hi - the has been checked into our code. It will reach production PBI clusters in three weeks. thx!

**Comment by verneroberts** [comment] 2017-02-26 19:09
@AviSander does anything need to change in this code for the fix to work or is the fix inside PowerBI?

**Comment by AviSander** [comment] 2017-02-27 06:53
no - the issue is PBI internal only. Hence no change required for the custom visuals code.

**Comment by willyt150** [comment] 2017-04-04 20:35
Is this the same issue ([#10](https://github.com/Microsoft/powerbi-visuals-utils-tooltiputils/issues/10)) as what I submitted in the [powerbi-visuals-utils-tooltiputils](https://github.com/Microsoft/powerbi-visuals-utils-tooltiputils) repository? If so it doesn't appear to have been fixed.

Is that repository active?

**Comment by willyt150** [comment] 2017-04-05 15:44
The April 2017 update for the Power BI desktop application fixed my tooltip positioning issue. The March 2017 version still had it.

Thanks!

**Closed** 2017-04-06 08:06 UTC
Labels: bug
